### ISSUE TITLE
SelectionActionBar.tsx / MergingLineCard.tsx fail to compile (Cannot find namespace 'JSX'); AutoItemizeLineList passes unknown sourceCount prop

### ISSUE THREAD

**Issue by steilerDev** [steilerDev/cornerstone#1800]
**[qa-integration-tester]**

# BUG: Two new Story #1797 components fail to compile

**Severity**: Blocker
**Component**: Frontend UI — `client/src/components/SelectionActionBar/SelectionActionBar.tsx`, `client/src/components/autoItemize/MergingLineCard.tsx`, `client/src/components/autoItemize/AutoItemizeLineList.tsx`
**Found in**: Writing/running `SelectionActionBar.test.tsx` (new), `MergingLineCard.test.tsx` (new), and extending `AutoItemizeLineList.test.tsx`.

## Steps to Reproduce

1. On branch `feat/1797-auto-itemize-merge-line-items`, run `npx tsc -p client/tsconfig.json --noEmit`.
2. Observe the errors below.

## Expected Behavior

Both new shared components compile cleanly and can be rendered/tested.

### 1. `JSX.Element` return type annotation doesn't compile

```
client/src/components/SelectionActionBar/SelectionActionBar.tsx(23,30): error TS2503: Cannot find namespace 'JSX'.
client/src/components/autoItemize/MergingLineCard.tsx(10,69): error TS2503: Cannot find namespace 'JSX'.
```

Both files declare an explicit `: JSX.Element` return type on their component function, e.g.:
```ts
export function SelectionActionBar({ ... }: SelectionActionBarProps): JSX.Element { ... }
export function MergingLineCard({ caption }: MergingLineCardProps): JSX.Element { ... }
```
No other component in `client/src/components/` uses this pattern (checked `Skeleton.tsx`, `Modal.tsx`, `EmptyState.tsx` — all omit an explicit return type and let TypeScript infer it). With this project's React 19 / `@types/react` setup, the bare global `JSX` namespace is not available this way; the fix is simply to remove the `: JSX.Element` annotation (matching every other shared component's convention), or import `type { ReactElement }` and use that instead.

### 2. `AutoItemizeLineList.tsx` passes an undeclared `sourceCount` prop to `MergingLineCard`

```
client/src/components/autoItemize/AutoItemizeLineList.tsx(143,21): error TS2322: Type '{ key: string; sourceCount: number; caption: string; }' is not assignable to type 'IntrinsicAttributes & MergingLineCardProps'.
  Property 'sourceCount' does not exist on type 'IntrinsicAttributes & MergingLineCardProps'.
```

`AutoItemizeLineList.tsx` line ~143 renders:
```tsx
<MergingLineCard
  key={line.rowId}
  sourceCount={line.mergeSourceLines?.length ?? 0}
  caption={t('autoItemize.mergingCaption', { count: line.mergeSourceLines?.length ?? 0 })}
/>
```
but `MergingLineCardProps` only declares `caption: string` — `sourceCount` was never added to the props interface (and appears unused inside the component body too). Either drop the extra prop from the call site, or add `sourceCount?: number` to `MergingLineCardProps` if it's meant to be used (e.g., for a data attribute).

## Environment

- Browser: N/A (TypeScript compile-time)
- Docker: no

## Evidence

Because `AutoItemizeLineList.tsx` fails `tsc`, every test that renders it also fails to run:
- `client/src/components/autoItemize/AutoItemizeLineList.test.tsx` — all 34 tests (20 pre-existing + 14 new merge/pending/error-row tests added in this story) fail to compile.
- `client/src/components/SelectionActionBar/SelectionActionBar.test.tsx` (new, 7 tests) and `client/src/components/autoItemize/MergingLineCard.test.tsx` (new, 6 tests) fail to compile on their own component files directly.

This also means the `Quality Gates` `typecheck` CI step will fail for this branch.

## Notes

All new QA tests for these components were written correctly against the intended/spec behavior (checkbox/state props, Skeleton+Spinner+aria-busy, SelectionActionBar count/clear/children) and will pass once these compile errors are fixed.

Co-Authored-By: Claude qa-integration-tester (Sonnet 4.5) <noreply@anthropic.com>

**Comment by steilerDev** [comment]
Fixed in PR #1803 (merged to beta).
