### ISSUE TITLE
TypeScript errors in AutoItemizeLineCard: wrong prop destructuring name and BudgetSource/Vendor shape mismatch

### ISSUE THREAD

**Issue by steilerDev** [steilerDev/cornerstone#1748]
# BUG: AutoItemizeLineCard.tsx has 3 TypeScript errors blocking CI typecheck

**Severity**: Critical
**Component**: Frontend UI — AutoItemize
**Found in**: Static Analysis (typecheck) on PR #1747, introduced in commit 5edc19fe

## Steps to Reproduce

1. Run \`npx tsc --noEmit -p client/tsconfig.json\` in the worktree
2. Observe errors at \`client/src/components/autoItemize/AutoItemizeLineCard.tsx\`

## Expected Behavior

\`client\` typecheck passes with zero errors.

## Actual Behavior

3 TypeScript errors block CI Static Analysis:

**Error 1** (line 48, TS2339): Property \`_onQueueNewBudgetLine\` does not exist on type \`AutoItemizeLineCardProps\`.

The interface declares \`onQueueNewBudgetLine\` (no underscore), but the destructuring pattern uses \`_onQueueNewBudgetLine\` (with underscore). Fix: change destructuring to \`onQueueNewBudgetLine: _onQueueNewBudgetLine,\` or remove the renaming.

**Error 2** (line 273, TS2322): Type \`{ id: string; name: string; isDiscretionary?: boolean }[]\` is not assignable to \`BudgetSource[]\`.

The \`budgetSources\` prop passed to the embedded \`BudgetLineForm\` uses a short-form shape from the card\'s own interface, but \`BudgetLineFormProps.budgetSources\` expects the full \`BudgetSource[]\` type (which has \`sourceType\`, \`totalAmount\`, \`usedAmount\`, \`availableAmount\`, etc.).

**Error 3** (line 274, TS2322): Type with short-form vendor shape is not assignable to \`Vendor[]\`.

Same issue — the \`vendors\` prop passed to embedded \`BudgetLineForm\` uses a minimal shape, but \`BudgetLineFormProps.vendors\` expects full \`Vendor[]\` (which has \`phone\`, \`email\`, \`address\`, \`notes\`, etc.).

## Environment

- Branch: \`fix/1737-1738-itemize-budget-vat\`
- Commit introduced: \`5edc19fe\` (fix(budget): fix VAT itemization and add inline budget line form)

## Evidence

CI Static Analysis failure on PR #1747, run https://github.com/steilerDev/cornerstone/actions/runs/27721817091

```
src/components/autoItemize/AutoItemizeLineCard.tsx(48,3): error TS2339: Property '_onQueueNewBudgetLine' does not exist on type 'AutoItemizeLineCardProps'.
src/components/autoItemize/AutoItemizeLineCard.tsx(273,15): error TS2322: Type '{ id: string; name: string; isDiscretionary?: boolean | undefined; }[]' is not assignable to type 'BudgetSource[]'.
src/components/autoItemize/AutoItemizeLineCard.tsx(274,15): error TS2322: Type '{ id: string; name: string; trade?: ... }[]' is not assignable to type 'Vendor[]'.
```

## Notes

These errors were introduced in production commit \`5edc19fe\`. The \`AutoItemizePage.tsx\` also has 10 additional TypeScript errors (same commit) that may need to be addressed together.

The embedded \`BudgetLineForm\` in \`AutoItemizeLineCard\` passes partial-shape arrays for \`budgetSources\` and \`vendors\`. The fix options are:
1. Widen \`BudgetLineFormProps\` to accept partial shapes (pick only the fields actually used)
2. Or pass full-shape data by routing complete \`BudgetSource[]\` and \`Vendor[]\` objects from the parent page through the card

**Comment by steilerDev** [comment]
Verified fixed on `beta` after #1747 merged. `client/src/components/autoItemize/AutoItemizeLineCard.tsx` now destructures `onQueueNewBudgetLine: _onQueueNewBudgetLine` correctly, and the `BudgetSource[]`/`Vendor[]` props passed to the embedded `BudgetLineForm` use the full shapes. No TS errors remain. Closing as resolved.
